BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `subcategories` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`categoryId`	INTEGER NOT NULL,
	`name`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `expenses` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`purchaseDate`	INTEGER NOT NULL,
	`updatedDate`	INTEGER NOT NULL,
	`categoryId`	INTEGER,
	`subcategoryId`	INTEGER,
	`price`	NUMERIC NOT NULL,
	`quantity`	INTEGER NOT NULL,
	`sum`	NUMERIC NOT NULL,
	`description`	TEXT NOT NULL,
	`notes`	TEXT
);
CREATE TABLE IF NOT EXISTS `categories` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL
);
COMMIT;
